### ISSUE TITLE
Missing STL file

### ISSUE THREAD

**Issue by normansta** [PCrnjak/Differential-robot-wrist#1]
Is an STL file available for this component? 
![image](https://github.com/PCrnjak/Differential-robot-wrist/assets/115659350/4e80c2cc-3287-4193-92a1-639d736cce64)

Additionally, would it be possible to prove STEP files for the hardware?

**Comment by PCrnjak** [comment]
It has been added. Only stl files are available at this moment

**Comment by normansta** [comment]
Thank you. Please let me know if you make the STEP files available for sale on your website or elsewhere.
